services:
  rabbitmq-1:
    image: rabbitmq:4.0.1-management
    hostname: rabbitmq-1
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    volumes:
      - ${PWD}/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ${PWD}/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - ${PWD}/data/rabbitmq-1:/var/lib/rabbitmq/
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - rabbitmq-cluster

  rabbitmq-2:
    image: rabbitmq:4.0.1-management
    hostname: rabbitmq-2
    depends_on:
      - rabbitmq-1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq-1
    volumes:
      - ${PWD}/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ${PWD}/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - ${PWD}/data/rabbitmq-2:/var/lib/rabbitmq/
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - rabbitmq-cluster

  rabbitmq-3:
    image: rabbitmq:4.0.1-management
    hostname: rabbitmq-3
    depends_on:
      - rabbitmq-1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq-1
    volumes:
      - ${PWD}/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ${PWD}/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - ${PWD}/data/rabbitmq-3:/var/lib/rabbitmq/
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - rabbitmq-cluster

  haproxy:
    image: haproxy:2.8.11
    volumes:
      - ${PWD}/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq-1
      - rabbitmq-2
      - rabbitmq-3
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - rabbitmq-cluster

networks:
  rabbitmq-cluster:
